Turing/2module/projects/fourteeners/config/routes.rb
Rails.application.routes.draw do
  resources :fourteeners
end

Turing/2module/projects/fourteeners/app/models/county.rb
class County < ActiveRecord::Base
  has_many :fourteeners
end

Turing/2module/projects/fourteeners/app/models/fourteener.rb
class Fourteener < ActiveRecord::Base
  belongs_to :county
end

Turing/2module/projects/fourteeners/app/controllers/fourteeners_controller.rb
class FourteenersController < ApplicationController
  def index
    @fourteeners = Fourteener.all
  end

  def new
    @fourteener = Fourteener.new
  end

  def create
    @fourteener = Fourteener.new(fourteener_params)
    if @fourteener.save
      redirect_to @fourteener
    else
      render :new
    end
  end

  def show
    @fourteener = Fourteener.find(params[:id])
  end

  def edit
    @fourteener = Fourteener.find(params[:id])
  end

  def update
    @fourteener = Fourteener.find(params[:id])
    @fourteener.update(fourteener_params)
    redirect_to @fourteener
  end

  private

  def fourteener_params
    params.require(:fourteener).permit(:name, :elevation, :image)
  end
end

Turing/2module/projects/fourteeners/app/views/fourteeners/edit.html.erb
<h1>Edit this Mountain</h1>
<%= form_for(@fourteener) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :elevation %>
  <%= f.text_field :elevation %>

  <%= f.label :image %>
  <%= f.text_field :image %>

  <%= f.submit %>
<% end %>

Turing/2module/projects/fourteeners/app/views/fourteeners/index.html.erb
<% @fourteeners.each do |mtn| %>
<%=  mtn.name %>
<%=  mtn.elevation %>
<%=  image_tag mtn.image %>
<% end %>

Turing/2module/projects/fourteeners/app/views/fourteeners/new.html.erb
<h1>New Fourteener</h1>

<%= form_for(@fourteener) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :elevation %>
  <%= f.text_field :elevation %>

  <%= f.label :image %>
  <%= f.text_field :image %>

  <%= f.submit %>
<% end %>

Turing/2module/projects/fourteeners/app/views/fourteeners/show.html.erb
<h1><%= "#{@fourteener.name}: #{@fourteener.elevation}ft" %></h1>
<%= image_tag @fourteener.image %>
<%= link_to "Edit", edit_fourteener_path(@fourteener) %>
<%= link_to "Delete", fourteener_path(@fourteener), method: :delete %>