Turing/2module/tool_chest/config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :tools
  end
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
end

Turing/2module/tool_chest/app/models/tool.rb
class Tool < ActiveRecord::Base
  validates :name, presence: true

  belongs_to :user
end

Turing/2module/tool_chest/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :tools
end

Turing/2module/tool_chest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :most_recent_tool

  def most_recent_tool
    if session[:most_recent_tool_id] != nil
      Tool.find(session[:most_recent_tool_id])
    else
      Tool.new
    end
  end
end

Turing/2module/tool_chest/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])

    if @user && @user.authenticate(params[:session][:password])
      flash[:notice] = "Welcome #{@user.username}"
      session[:user_id] = @user.id
      redirect_to user_tools_path(@user.id)
    else
      flash[:error] = "Invalid Login"
      render :new
    end
  end

  def destroy
    session.clear

    redirect_to root_path
  end
end

Turing/2module/tool_chest/app/controllers/tools_controller.rb
class ToolsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @tools = @user.tools
  end

  def destroy
    Tool.find(params[:id]).destroy
    redirect_to user_tools_path
  end

  def new
    @user = User.find(params[:user_id])
    @tool = @user.tools.new
  end

  def create
    @user = User.find(params[:user_id])
    @tool = @user.tools.new(tool_params)
    if @tool.save
      session[:most_recent_tool_id] = @tool.id
      flash[:notice] = "you have successfully created a tool"
      redirect_to user_tools_path(@user)
    else
      flash[:error] = @tool.errors.full_messages.join(", ")
      redirect_to new_user_tool_path
    end
  end

  def show
    @tool = User.tools.find(params[:id])
  end

  # def clear_session
  #   session.delete(:most_recent_tool_id)
  # end

  private

  def tool_params
    params.require(:tool).permit(:name, :price, :quantity)
  end
end

Turing/2module/tool_chest/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome #{@user.username}"
      redirect_to user_tools_path(@user)
    else
      flash.now[:error] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

Turing/2module/tool_chest/app/views/tools/index.html.erb
<h1>All Tools</h1>

<div class="notice">
  <%= flash[:notice] %>
</div>
<div class="error">
  <%= flash[:error] %>
</div>

<%= link_to "Create New Tool", new_user_tool_path %>

<div class="tool_info">
<% @tools.each do |tool| %>
  <p><%= link_to "#{tool.name}", user_tool_path(@user, tool) %>
  price: <%= tool.price %>
  quantity: <%= tool.quantity %></p>
<% end %>
</div>

Turing/2module/tool_chest/app/views/tools/new.html.erb
<div class="error">
  <%= flash[:error] %>
</div>
<%= form_for [@user, @tool] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>

  <%= f.submit %>

<% end %>

Turing/2module/tool_chest/app/views/tools/show.html.erb
<div class="notice">
  <%= flash[:notice] %>
</div>
<div class="tool_info">
  <%= @tool.name %>
  <%= @tool.price %>
  <%= @tool.quantity %>
</div>

Turing/2module/tool_chest/app/views/users/new.html.erb
<h1>Make a New User</h1>
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.text_field :password %>

  <%= f.submit %>
<% end %>